name: Build standalone server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: yarn install

    - name: Build standalone server
      run: yarn build

    - name: Archive standalone server
      run: |
        mv .next/standalone nextchat
        mv .next/static nextchat/.next
        mv public nextchat
        tar -czf nextchat.tar.gz nextchat

    - name: Get version
      id: get_version
      run: |
        echo version=$(node -pe 'JSON.parse(process.argv[1]).package.version' "$(cat src-tauri/tauri.conf.json)") >> "$GITHUB_OUTPUT"

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        files: nextchat.tar.gz

